Detect API key from config if possible and not overriden by envvar

diff --git a/datadog-notify b/datadog-notify
--- a/datadog-notify
+++ b/datadog-notify
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-api_key="$DATADOG_API_KEY"
-
 function usage(){
   echo "Usage:" >&2
   echo "$0 title message [error|warning|info|success] [tags...]" >&2
@@ -20,8 +18,17 @@ title="$1"
 message="$2"
 alert_type="$3"
 
-if [[ -z "$DATADOG_API_KEY" ]]; then
-  echo "Please provide your API key in the environment variabe DATADOG_API_KEY" >&2
+dd_config='/etc/dd-agent/datadog.conf'
+
+if [[ -n "$DATADOG_API_KEY" ]]; then
+  api_key="$DATADOG_API_KEY"
+else
+  api_key=$(grep '^api_key:' $dd_config | cut -d' ' -f2)
+fi
+
+if [[ -z "$api_key" ]]; then
+  echo "Could not find Datadog API key in either ${dd_config} or DATADOG_API_KEY environment variable." >&2
+  echo "Please provide your API key in one of these locations" >&2
   usage
 fi
 
